// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Area = 100,
                            CreatedDate = new DateTime(2023, 6, 3, 21, 55, 38, 686, DateTimeKind.Local).AddTicks(2521),
                            Detail = "Villa con vista al mar",
                            ImageUrl = "",
                            Name = "Villa Real",
                            Occupants = 5,
                            Rate = 15.0,
                            UpdateDate = new DateTime(2023, 6, 3, 21, 55, 38, 686, DateTimeKind.Local).AddTicks(2532)
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Area = 100,
                            CreatedDate = new DateTime(2023, 6, 3, 21, 55, 38, 686, DateTimeKind.Local).AddTicks(2534),
                            Detail = "Villa en la cordillera de los Andes",
                            ImageUrl = "",
                            Name = "Villa Alta Cumbre",
                            Occupants = 5,
                            Rate = 15.0,
                            UpdateDate = new DateTime(2023, 6, 3, 21, 55, 38, 686, DateTimeKind.Local).AddTicks(2535)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
